version: "3.8"

services:
  mikhmon:
    container_name: Mikhmon
    build: .
    # image: rizkikotet/mikhmon:latest
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - mikhmon_data:/var/www/html

volumes:
  mikhmon_data: