services:
  mikhmon:
    container_name: Mikhmon
    pull_policy: always
    build: .
    #image: rizkikotet/mikhmon:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - mikhmon_data:/var/www/html

volumes:
  mikhmon_data:
    driver: local