services:
  mikhmon:
    container_name: Mikhmon
    pull_policy: always
    build: .
    #image: rizkikotet/mikhmon:latest
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command: 
      - /bin/bash
      - -c
      - /etc/supervisor/conf.d/supervisord.conf
    volumes:
      - mikhmon_data:/var/www/html

volumes:
  mikhmon_data: